name: Test
on: [push]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check run
        run: go version
      - name: install wire
        run: go get -u github.com/google/wire/cmd/wire
      - name: run wire
        run: $(go env GOPATH)/bin/wire
        working-directory: ./
      - name: Install golangci-lint
        run: |
          curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.17.1
          sudo mv ./bin/golangci-lint $GOPATH/bin/
      - name: Run golangci-lint
        run: >
          golangci-lint run \
            --tests \
            --enable-all \
            --disable gochecknoglobals \
            --disable gochecknoinits
        working-directory: ./
      #- name: golangci-lint
      #  uses: golangci/golangci-lint-action@v2
      #  with:
      #    version: v1.29
      #    working-directory: ./
