name: Test
on: [push]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install wire
        run: go get -u github.com/google/wire/cmd/wire
      - name: run wire
        run: $(go env GOPATH)/bin/wire
        with:
          working-directory: ./
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          working-directory: ./
